import {
  useGetPaymentQuery,
  useGetPaymentsQuery,
  useGetCustomerPaymentsQuery,
  useGetPaymentMethodsQuery,
  useGetInvoiceQuery,
  useGetCustomerInvoicesQuery,
  useCreatePaymentMutation,
  useRefundPaymentMutation,
  useAddPaymentMethodMutation,
  useRemovePaymentMethodMutation,
  useSetDefaultPaymentMethodMutation,
  useGenerateInvoiceMutation,
  useMarkInvoiceAsPaidMutation,
  useCancelInvoiceMutation,
} from "@/graphql/api";

export {
  useGetPaymentQuery,
  useGetPaymentsQuery,
  useGetCustomerPaymentsQuery,
  useGetPaymentMethodsQuery,
  useGetInvoiceQuery,
  useGetCustomerInvoicesQuery,
  useCreatePaymentMutation,
  useRefundPaymentMutation,
  useAddPaymentMethodMutation,
  useRemovePaymentMethodMutation,
  useSetDefaultPaymentMethodMutation,
  useGenerateInvoiceMutation,
  useMarkInvoiceAsPaidMutation,
  useCancelInvoiceMutation,
};
